"""
Django settings for Hotel project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_DIR=BASE_DIR/'static'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l3+rdgo4rz8tk)u%wv7i=3fqv#xmx5pe(lebp_6_@g7*7y4h6s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [                
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Hotel',
    'visom6',
]

# settings.py

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # For example, using Gmail
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'xyz@gmail.com'
EMAIL_HOST_PASSWORD = '11111'
DEFAULT_FROM_EMAIL = 'Visom6 Luxury Hotel <xyz@gmail.com>'


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Hotel.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Hotel.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        #'NAME': 'visom',
        #'USER': 'root',
        #'PASSWORD': '123456789',
        #'PORT':'3306',
        #'HOST':'127.0.0.1',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# settings.py
JAZZMIN_SETTINGS = {
    "site_title": "Hotel Admin",
    "site_header": "Hotel Booking Dashboard",
    "welcome_sign": "Welcome to the Hotel Admin Panel",
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Bookings", "url": "admin:visom6_booking_changelist"},
        {"name": "Rooms", "url": "admin:visom6_room_changelist"},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "order_with_respect_to": ["visom6.Booking", "visom6.Room", "auth"],
    "icons": {
        "visom6.Booking": "fas fa-bed",
        "visom6.Room": "fas fa-door-open",
    },
    "dashboard_widgets": [
        {
            "type": "html",
            "content": """
            <div class='row'>
                <div class='col-lg-3 col-6'>
                    <div class='small-box bg-info'>
                        <div class='inner'>
                            <h3>{{ total_users }}</h3>
                            <p>Registered Users</p>
                        </div>
                        <div class='icon'>
                            <i class='fas fa-users'></i>
                        </div>
                        <a href='/admin/auth/user/' class='small-box-footer'>More info <i class='fas fa-arrow-circle-right'></i></a>
                    </div>
                </div>
                <div class='col-lg-3 col-6'>
                    <div class='small-box bg-success'>
                        <div class='inner'>
                            <h3>{{ total_bookings }}</h3>
                            <p>Total Bookings</p>
                        </div>
                        <div class='icon'>
                            <i class='fas fa-bed'></i>
                        </div>
                        <a href='/admin/visom6/booking/' class='small-box-footer'>More info <i class='fas fa-arrow-circle-right'></i></a>
                    </div>
                </div>
                <!-- Add more boxes as needed -->
            </div>
            """,
        },
        {
            "type": "html",
            "content": "<h3>Welcome to the Hotel Booking Dashboard</h3>",
        },
        {
            "type": "model",
            "model": "visom6.Booking",
            "params": {
                "title": "Recent Bookings",
                "queryset": "visom6.Booking.objects.order_by('-check_in_date')[:5]",
                "fields": ["customer_name", "room", "check_in_date", "check_out_date"],
            },
        },
        {
            "type": "chart",
            "model": "visom6.Booking",
            "params": {
                "title": "Monthly Bookings",
                "chart_type": "bar",
                "x_field": "check_in_date",
                "y_field": "id",  # Assuming 'id' counts the bookings
                "chart_color": "#3498DB",
            },
        },
        {
            "type": "model",
            "model": "visom6.Room",
            "params": {
                "title": "Room Availability",
                "queryset": "visom6.Room.objects.filter(is_available=True)",
                "fields": ["room_number", "room_type"],
            },
        },
    ],
    "custom_css": None,
    "custom_js": None,
}


JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",
    "dark_mode_theme": "cyborg",
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": True,
    "brand_colour": "navbar-success",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-success",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": True,
    "sidebar_nav_flat_style": False,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}
