# Generated by Django 5.0.7 on 2024-08-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('junior_suite', 'Junior Suite'), ('family_room', 'Family Room'), ('double_room', 'Double Room'), ('deluxe_room', 'Deluxe Room'), ('superior_room', 'Superior Room')], max_length=20, unique=True)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/')),
            ],
        ),
    ]
