# Generated by Django 5.0.7 on 2024-08-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visom6', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
        migrations.AddField(
            model_name='room',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
    ]
