# Generated by Django 5.0.7 on 2024-08-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visom6', '0002_room_image1_room_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_persons',
            field=models.CharField(default='1-2 Persons', max_length=10),
        ),
    ]
