# Generated by Django 5.0.7 on 2024-08-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visom6', '0003_room_max_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='max_persons',
            field=models.CharField(max_length=10),
        ),
    ]
