# Generated by Django 5.0.7 on 2024-08-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visom6', '0007_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_type', models.CharField(choices=[('birthday_hall', 'Birthday Celebration'), ('family_hall', 'Family Room'), ('office_hall', 'Office Conference'), ('social_hall', 'Social Events'), ('wedding_hall', 'Wedding Celebratiion')], max_length=20, unique=True)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='halls/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='halls/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='halls/')),
                ('max_persons', models.IntegerField()),
            ],
        ),
    ]
