# Generated by Django 5.0.7 on 2024-09-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visom6', '0011_alter_booking_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=8),
        ),
    ]
