# Generated by Django 5.0.7 on 2024-09-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visom6', '0013_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='booked_rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='total_rooms',
            field=models.IntegerField(default=0),
        ),
    ]
