# Generated by Django 5.0.7 on 2024-10-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visom6', '0014_room_booked_rooms_room_total_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_payment_id', models.CharField(max_length=50)),
                ('razorpay_order_id', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='failed', max_length=10),
        ),
    ]
