# Generated by Django 5.0.7 on 2024-10-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visom6', '0015_payment_booking_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('success', 'Success'), ('pending', 'Pending'), ('failed', 'Failed')], default='failed', max_length=10),
        ),
    ]
